version: "3.0"
services:
  es:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    networks:
      - es-net
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.5.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - es
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge